### ISSUE TITLE
not found by vcpkg

### ISSUE THREAD

**Issue by NicolasRodriguez676** [JamesBoer/ImFrame#2]
Hello, could you make this repo visible to vcpkg?

or...
I'm relatively new to vcpkg/cmake so if you know of a good resource to figure out how to incorporate it into a separate cmake project, that'd be awesome

**Comment by JamesBoer** [comment]
I'm not familiar with using vcpkg, so I'd have to look into that.  Long term, it's probably a good idea to try to support some of the more popular package managers.

In the meantime, incorporating ImFrame into a separate CMake-based project is relatively straightforward.  It was designed to be easy to integrate.

In your own CMake based project, you just need to add ImFrame using (assuming it's located in the folder /External/ImFrame):

`add_subdirectory("External/ImFrame")`

I'll consider adding a starter project which uses ImFrame that shows how to do this.  I kind of already did this with the library's sample apps, but it may not be as obvious how to extract those into their own CMake project.

**Comment by NicolasRodriguez676** [comment]
Thank you.

It took quite a bit more to add it in though. How did you learn cmake?

**Comment by JamesBoer** [comment]
Slowly... painfully...  I started with some very simple Hello World type apps, getting them compiling on Windows, Mac, and Linux platforms.  Then I figured out how to get an app plus a static library compiling.  The first library I converted was my scripting language [Jinx](https://github.com/JamesBoer/Jinx), where I figured out a number of tricks and patterns I'm still using.  After that, I managed to get my entire game engine and game building with CMake, which really stretched my knowledge, like compiling shader headers, creating sym links, and other esoteric stuff that's harder to figure out.

That entire process took up a lot of my free time over quite a few months.  It's helpful if you have a series of increasingly larger and more complex projects you can work through.

**Comment by NicolasRodriguez676** [comment]
Thank you. Ill try doing a smaller part of my project with cmake and then later try adding it along with yours.
It appears lots of people learn this way. Most of what I know is learned like this but with moreover 'unsuccessful' projects

Thank you for your time
