### ISSUE TITLE
Question : does imframe support the docking branch of imgui? 

### ISSUE THREAD

**Issue by rowlesmr** [JamesBoer/ImFrame#3]
Hi James
Looking at using your framework to build my idea for a program.

Do you support the docking branch of imgui?

Thanks

Matthew

**Comment by JamesBoer** [comment]
Yes, ImFrame is currently built with the docking branch of imgui.  

It's been a while, so I should probably update to the latest version as well.

**Comment by rowlesmr** [comment]
Ta a lot. Then I shall proceed and see if I can make it work.
